spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/todo}
    password: ${DATABASE_PASSWORD:root}
    username: ${DATABASE_USERNAME:root}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update